server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
  servlet:
    session:
      cookie:
        http-only: false

version: v1.3.5
version.date: 2021/04/12
upload.temp.path: /temp/
default:
  server:
    address: http://node-1:8080
    group: group1

spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  #引入sql性能分析插件p6spy后 需要更换驱动
    url: jdbc:mysql:///fileSystem?useSSL=true   #引入sql性能分析插件p6spy后 需要更换url
    #    url: jdbc:p6spy:mysql://localhost:3306/world
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: adminadmin


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full


    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #逻辑删除设置
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以不加@TableLogic在实体类字段上)
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:com/study/mapper/xml/*.xml

logging:
  level:
    com.graduation: debug
  file:
    name: ./logs/debug.log

pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql