server:
  tomcat:
    uri-encoding: UTF-8
    max-keep-alive-requests: -1
    connection-timeout: 15000
  port: 8081
  servlet:
    session:
      cookie:
        http-only: false

# 用户离线配置
default:
  # 部署服务器地址
  ipaddr: 1.15.221.117
  server:
    port: 8080
    address: http://1.15.221.117:8080
    group: group1
    peerAddress: http://1.15.221.117:8080
    # nginx 反向代理  -> 8085 - 8080
    proxy: http://1.15.221.117:8085

spring:
  aop:
    proxy-target-class: true
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  #引入sql性能分析插件p6spy后 需要更换驱动
    url: jdbc:mysql:///filesystem?useSSL=true   #引入sql性能分析插件p6spy后 需要更换url
    #    url: jdbc:p6spy:mysql://localhost:3306/world
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: adminadmin
  #redis 配置
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
    password: adminadmin


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full


    #日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #逻辑删除设置
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以不加@TableLogic在实体类字段上)
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:com/graduation/mapper/xml/*.xml

#logging:
#  level:
#    com.graduation: debug
#  file:
#    name: ./logs/debug.log

pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

solr:
  collection: collection1